apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: k8s-multi-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s-test.razul.dev
  dnsNames:
    - k8s-test.razul.dev
    - www.k8s-test.razul.dev
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s-test.razul.dev
          - www.k8s-test.razul.dev